// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Login");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, "login", React.createElement("input", {
                              value: self[/* state */1][/* login */0],
                              onChange: (function (ev) {
                                  return Curry._1(self[/* send */3], /* SetLogin */Block.__(0, [ev.target.value]));
                                })
                            }), "password", React.createElement("input", {
                              type: "password",
                              value: self[/* state */1][/* password */1],
                              onChange: (function (ev) {
                                  return Curry._1(self[/* send */3], /* SetPassword */Block.__(1, [ev.target.value]));
                                })
                            }));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* login */"",
                      /* password */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* login */state[/* login */0],
                            /* password */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* login */action[0],
                            /* password */state[/* password */1]
                          ]]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
